  float photonIso_2, puIso_2, chargedIso_2, neutralIso_2,m_sv,m_sv_UP,m_sv_DOWN,pt_sv,pt_sv_UP,pt_sv_DOWN, metcor,metcorphi;
  int gen_match_1, gen_match_2;
  float byCombinedIsolationDeltaBetaCorrRaw3Hits_2, byIsolationMVA3oldDMwLTraw_2;
  float pt_1,pt_2,px_1,px_2,py_1,py_2,pz_1,pz_2,eta_1,eta_2,phi_1,phi_2,iso_1,e_1,e_2,m_1,m_2;
  //float pu_weight, trg_weight, aMCatNLO_weight;
  //bool dilepton_veto, extraelec_veto, extramuon_veto;
  bool isZmt, isZet;
  int nbtag;
  float gentau_vispt;
  int run, lumi, evt;
  int nup,njets;
  float npv, pt_tt,mt_2,jpt_1,jdeta,mjj;
  float q_1,q_2;
  float met, metphi, met_px, met_py;
  float tau_HPSisoVTightMVAold, tau_HPSisoLooseMVAold, tau_HPSisoMediumMVAold, tau_HPSisoTightMVAold;
  float tau_HPSisoVTightMVAnew, tau_HPSisoLooseMVAnew, tau_HPSisoMediumMVAnew, tau_HPSisoTightMVAnew;
  float tau_HPSisoVTightMVAolddR03, tau_HPSisoLooseMVAolddR03, tau_HPSisoMediumMVAolddR03, tau_HPSisoTightMVAolddR03;
  float byLooseCombinedIsolationDeltaBetaCorr3Hits_2,byMediumCombinedIsolationDeltaBetaCorr3Hits_2,byTightCombinedIsolationDeltaBetaCorr3Hits_2,byLooseCombinedIsolationDeltaBetaCorr3HitsdR03_2,byMediumCombinedIsolationDeltaBetaCorr3HitsdR03_2,byTightCombinedIsolationDeltaBetaCorr3HitsdR03_2;
  float byVLooseIsolationMVArun2v1DBdR03oldDMwLT_2,byVLooseIsolationMVArun2v1DBoldDMwLT_2,byVLooseIsolationMVArun2v1DBnewDMwLT_2;
  float byMediumIsolationMVArun2v1DBdR03oldDMwLT_2,byMediumIsolationMVArun2v1DBoldDMwLT_2,byMediumIsolationMVArun2v1DBnewDMwLT_2;
  float byLooseIsolationMVArun2v1DBdR03oldDMwLT_2,byLooseIsolationMVArun2v1DBoldDMwLT_2,byLooseIsolationMVArun2v1DBnewDMwLT_2;
  float byTightIsolationMVArun2v1DBdR03oldDMwLT_2,byTightIsolationMVArun2v1DBoldDMwLT_2,byTightIsolationMVArun2v1DBnewDMwLT_2;
  float byVTightIsolationMVArun2v1DBdR03oldDMwLT_2,byVTightIsolationMVArun2v1DBoldDMwLT_2,byVTightIsolationMVArun2v1DBnewDMwLT_2;
  float againstElectronVLooseMVA6_2,againstElectronLooseMVA6_2,againstElectronMediumMVA6_2,againstElectronTightMVA6_2,againstElectronVTightMVA6_2;
  float againstMuonLoose3_2,againstMuonTight3_2, passEle25;
  int numChargedIsoCone_2, numChargedSignalCone_2;
  float decayMode_2,l2_decayMode;
  float trackpt_2,m_vis;
  int tau_id;
  float decayModeFindingNewDMs_2,decayModeFinding_2;
  float puweight;
  float npu;
  int NUP;

